Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: false

Style/TrailingComma:
  Enabled: false
